## べき乗法

行列Aの最大固有値を出力する

### べき乗法のアルゴリズム

１）A,x(0)を入力する

２）k=0,1,2,....に対して

　　
  a)y(k)=Ax(k),　　λ=(y(k),y(k))/(y(k),x(k))
  
 　 　b)x(k+1)=y(k)/|y(k)|
 
 3)λの値が収束すれば反復を終了する

In [4]:
import math

NM=3
y=[0]*NM
EPS=1.0E-6

#1
n=3
a=[[11,7,-5],[0,10,-1],[2,8,3]]

x=[1.0]*n

#2
kmax=200
lambda1 = 10000
lambda2 = 10000
for k in range(1,kmax+1):
    gosa=0
    #(a) y=Ax
    for i in range(n):
        y[i]=0
        for j in range(n):
            y[i]+=a[i][j]*x[j]
            
    #(a) λ=(y,y)/(y,x)
    sum1 = 0
    sum2 = 0
    for i in range(n):
        sum1+=y[i]*y[i]
        sum2+=y[i]*x[i]
    lambda1 = sum1/sum2
    
    #(b)
    for i in range(n):
        x[i]=y[i]/math.sqrt(sum1)
    
    #3
    gosa=abs(lambda1-lambda2)/abs(lambda2)
    lambda2=lambda1
    if gosa < EPS:
        print("Converged!")
        print()
        break
        
    print(f'k={k:3} lambda={lambda1:10.6f}')
    
if k >= kmax:
    print()
    print("It didn't converged.")

k=  1 lambda= 11.971429
k=  2 lambda= 10.350360
k=  3 lambda=  9.592671
k=  4 lambda=  9.163960
k=  5 lambda=  8.895403
k=  6 lambda=  8.718297
k=  7 lambda=  8.600185
k=  8 lambda=  8.524295
k=  9 lambda=  8.481475
k= 10 lambda=  8.466440
k= 11 lambda=  8.475717
k= 12 lambda=  8.506305
k= 13 lambda=  8.554768
k= 14 lambda=  8.616742
k= 15 lambda=  8.686944
k= 16 lambda=  8.759671
k= 17 lambda=  8.829600
k= 18 lambda=  8.892562
k= 19 lambda=  8.945973
k= 20 lambda=  8.988843
k= 21 lambda=  9.021451
k= 22 lambda=  9.044896
k= 23 lambda=  9.060660
k= 24 lambda=  9.070301
k= 25 lambda=  9.075259
k= 26 lambda=  9.076766
k= 27 lambda=  9.075821
k= 28 lambda=  9.073206
k= 29 lambda=  9.069515
k= 30 lambda=  9.065187
k= 31 lambda=  9.060541
k= 32 lambda=  9.055801
k= 33 lambda=  9.051125
k= 34 lambda=  9.046613
k= 35 lambda=  9.042334
k= 36 lambda=  9.038323
k= 37 lambda=  9.034599
k= 38 lambda=  9.031168
k= 39 lambda=  9.028026
k= 40 lambda=  9.025160
k= 41 lambda=  9.022557
k= 42 lambda=  9

pythonのモジュールによる出力

In [7]:
import numpy as np
import numpy.linalg as LA
A = np.array([[11,7,-5],
             [0,10,-1],
             [2,8,3]])

w,v=LA.eig(A)
print(w)
print(v)

[7. 9. 8.]
[[-0.53452248 -0.57735027 -0.40824829]
 [-0.26726124  0.57735027 -0.40824829]
 [-0.80178373  0.57735027 -0.81649658]]


出力値wは行列Aの固有値となる

最大固有値が９であることがわかる

逆に最小固有値は７であることも同時にわかる