多くの数値計算法は最終的に連立１次方程式に帰着させることが多いのでこの分野において連立1次方程式はとても重要な分野である

連立1次方程式の解き方は未知の数にはよらないが、コンピュータで大次元の方程式を解く場合には、計算時間や記憶容量、計算速度の問題がつきもの。

連立1次方程式のコンピュータによる解き方は大別すると、反復法と消去法がある。

## ヤコビ法

In [38]:
import numpy as np

EPS = 1e-7
IMAX = 50
N = 4

A = np.zeros((N+1,N+1))
A[1][1]=9.0; A[1][2]=2.0;  A[1][3]=1.0;  A[1][4]=1.0
A[2][1]=2.0; A[2][2]=8.0;  A[2][3]=-2.0; A[2][4]=1.0
A[3][1]=-1.0;A[3][2]=-2.0; A[3][3]=7.0;  A[3][4]=-2.0
A[4][1]=1.0; A[4][2]=-1.0; A[4][3]=-2.0; A[4][4]=6.0

B = np.zeros(N+1)
B[1]=20;B[2]=16;B[3]=8;B[4]=17

X = np.zeros(N+1)
XN = np.zeros(N+1)

for i in range(IMAX):
    err=0
    for j in range(1,N+1):
        XN[j]=B[j]
        for k in range(1,j):
            XN[j]=XN[j]-A[j][k]*X[k]
        for k in range(j+1,N+1):
            XN[j]=XN[j]-A[j][k]*X[k]
        XN[j]=XN[j]/A[j][j]
        err=err+abs(XN[j]-X[j])
        
    if err<EPS:
        break
    else:
        for j in range(1,N+1):
            X[j]=XN[j]
            
    np.set_printoptions(precision=7, floatmode="fixed", suppress=True)
    print(i,X[1:N+1])

if i+1>=IMAX:
    print("It did not converged.")
else:
    print("It converged.")

0 [2.2222222 2.0000000 1.1428571 2.8333333]
1 [1.3359788 1.3759921 2.8412698 3.1772487]
2 [1.2477219 1.9791667 2.6346372 3.7870922]
3 [1.0688819 1.8733423 2.9686057 3.8334532]
4 [1.0501396 1.9957493 2.9260676 3.9569453]
5 [1.0139432 1.9743638 2.9936470 3.9662908]
6 [1.0101483 1.9991396 2.9850361 3.9912858]
7 [1.0028221 1.9948112 2.9987141 3.9931772]
8 [1.0020540 1.9998259 2.9969713 3.9982362]
9 [1.0005712 1.9989498 2.9997397 3.9986191]
10 [1.0004157 1.9999648 2.9993870 3.9996430]
11 [1.0001156 1.9997874 2.9999473 3.9997205]
12 [1.0000841 1.9999929 2.9998759 3.9999277]
13 [1.0000234 1.9999570 2.9999893 3.9999434]
14 [1.0000170 1.9999986 2.9999749 3.9999854]
15 [1.0000047 1.9999913 2.9999978 3.9999885]
16 [1.0000034 1.9999997 2.9999949 3.9999970]
17 [1.0000010 1.9999982 2.9999996 3.9999977]
18 [1.0000007 1.9999999 2.9999990 3.9999994]
19 [1.0000002 1.9999996 2.9999999 3.9999995]
20 [1.0000001 2.0000000 2.9999998 3.9999999]
21 [1.0000000 1.9999999 3.0000000 3.9999999]
22 [1.0000000 2.0000

In [25]:
A

array([[ 0.0000000,  0.0000000,  0.0000000,  0.0000000,  0.0000000],
       [ 0.0000000,  9.0000000,  2.0000000,  1.0000000,  1.0000000],
       [ 0.0000000,  2.0000000,  8.0000000, -2.0000000,  1.0000000],
       [ 0.0000000, -1.0000000, -2.0000000,  7.0000000, -2.0000000],
       [ 0.0000000,  1.0000000, -1.0000000, -2.0000000,  6.0000000]])

In [26]:
B

array([ 0.0000000, 20.0000000, 16.0000000,  8.0000000, 17.0000000])

In [28]:
import numpy as np

A = np.array([[9,2,1,1],
              [2,8,-2,1],
              [-1,-2,7,-2],
              [1,-1,-2,6]])

b = np.array([20,16,8,17])

x = np.linalg.solve(A,b)

print(x)

[1.0000000 2.0000000 3.0000000 4.0000000]


## ガウス・ザイデル法

In [41]:
import numpy as np

EPS = 1e-7
IMAX = 50
N = 4

A = np.zeros((N+1,N+1))
A[1][1]=9.0; A[1][2]=2.0;  A[1][3]=1.0;  A[1][4]=1.0
A[2][1]=2.0; A[2][2]=8.0;  A[2][3]=-2.0; A[2][4]=1.0
A[3][1]=-1.0;A[3][2]=-2.0; A[3][3]=7.0;  A[3][4]=-2.0
A[4][1]=1.0; A[4][2]=-1.0; A[4][3]=-2.0; A[4][4]=6.0

B = np.zeros(N+1)
B[1]=20;B[2]=16;B[3]=8;B[4]=17

X = np.zeros(N+1)
XN = np.zeros(N+1)

for i in range(IMAX):
    err=0
    for j in range(1,N+1):
        XN[j]=B[j]
        for k in range(1,j):
            XN[j]=XN[j]-A[j][k]*XN[k]
        for k in range(j+1,N+1):
            XN[j]=XN[j]-A[j][k]*XN[k]
        XN[j]=XN[j]/A[j][j]
        err=err+abs(XN[j]-X[j])
        
    if err<EPS:
        break
    else:
        for j in range(1,N+1):
            X[j]=XN[j]
            
    np.set_printoptions(precision=7, floatmode="fixed", suppress=True)
    print(i,X[1:N+1])

if i+1>=IMAX:
    print("It did not converged.")
else:
    print("It converged.")

0 [2.2222222 1.4444444 1.8730159 3.3280423]
1 [1.3233392 1.7214139 2.7746074 3.8245482]
2 [1.1064463 1.9389717 2.9476409 3.9546345]
3 [1.0244201 1.9864759 2.9866630 3.9892303]
4 [1.0056839 1.9965910 2.9967609 3.9974048]
5 [1.0014058 1.9991632 2.9992203 3.9993663]
6 [1.0003430 1.9997985 2.9998104 3.9998460]
7 [1.0000829 1.9999511 2.9999539 3.9999627]
8 [1.0000201 1.9999881 2.9999888 3.9999909]
9 [1.0000049 1.9999971 2.9999973 3.9999978]
10 [1.0000012 1.9999993 2.9999993 3.9999995]
11 [1.0000003 1.9999998 2.9999998 3.9999999]
12 [1.0000001 2.0000000 3.0000000 4.0000000]
13 [1.0000000 2.0000000 3.0000000 4.0000000]
It converged.
