## 変形コレスキー法

コレスキー法だと平方根の計算を必要であり、平方根の計算は剰余算に比べて時間がかかる上に制度的にも不利なので、コレスキー法を変形して剰余算に持っていくことを考える。

この場合、変形方法として（i,i）成分をDとしてU^(t)DU=Aのようにすると上手くいく。

In [8]:
import numpy as np

#元数
N=3

#問題設定
A=np.zeros((N+1,N+1))
B=np.zeros(N+1)
A[1][1]=1; A[1][2]=2; A[1][3]=1;
A[2][1]=2; A[2][2]=3; A[2][3]=1;
A[3][1]=1; A[3][2]=1; A[3][3]=4;

B[1]=2; B[2]=1; B[3]=7

U=np.zeros((N+1,N+1))
D=np.zeros((N+1,N+1))
X=np.zeros(N+1)
Z=np.zeros(N+1)

#DとUの計算
for i in range(1,N+1):
    U[i][i]=1
    
D[1][1]=A[1][1]
for j in range(2,N+1):
    U[1][j]=A[1][j]/D[1][1]

for i in range(2,N+1):
    sum = 0
    for m in range(1,i):
        sum=sum+U[m][i]*U[m][i]*D[m][m]
    D[i][i]=A[i][i]-sum
    
    if i!=N:
        for j in range(i+1,N+1):
            sum=0
            for m in range(1,i):
                sum=sum+U[m][j]*D[m][m]*U[m][i]
            U[i][j]=(A[i][j]-sum)/D[i][i]

#DとUの確認            
np.set_printoptions(precision=1,floatmode="fixed",suppress=True)
print("U=",U[1:N+1,1:N+1])
print("D=",D[1:N+1,1:N+1])

#前進消去法でZを計算
Z[1]=B[1]
for i in range(2,N+1):
    sum=0
    for m in range(1,i):
        sum=sum+U[m][i]*Z[m]
    Z[i]=B[i]-sum

#解を求める
X[N]=Z[N]/D[N][N]
for i in range(N-1,0,-1):
    sum=0
    for m in range(i+1,N+1):
        sum=sum+U[i][m]*X[m]
        X[i]=Z[i]/D[i][i]-sum
print("X=",X[1:N+1])

U= [[1.0 2.0 1.0]
 [0.0 1.0 1.0]
 [0.0 0.0 1.0]]
D= [[ 1.0  0.0  0.0]
 [ 0.0 -1.0  0.0]
 [ 0.0  0.0  4.0]]
X= [-2.0  1.0  2.0]
